import { useCallback, useEffect, useState } from 'react';
import { Button, Card, Empty, Form, Input, List, Select, Space, Upload, message } from 'antd';
import { DeleteOutlined, DownloadOutlined, UploadOutlined } from '@ant-design/icons';
import api from '../services/api';

const MedicalDocuments = () => {
  const [form] = Form.useForm(); const [file, setFile] = useState(); const [items, setItems] = useState([]); const [working, setWorking] = useState(false);
  const load = useCallback(async () => { try { setItems((await api.get('/api/medical-documents')).data.documents || []); } catch { message.error('Unable to load medical documents.'); } }, []);
  useEffect(() => { load(); }, [load]);
  const upload = async (values) => { if (!file) return message.error('Choose a document first.'); setWorking(true); try { const body = new FormData(); body.append('document', file); Object.entries(values).forEach(([key, value]) => body.append(key, value)); await api.post('/api/medical-documents', body, { headers: { 'Content-Type': 'multipart/form-data' } }); form.resetFields(); setFile(undefined); message.success('Document uploaded securely.'); load(); } catch (error) { message.error(error.response?.data?.message || 'Unable to upload document.'); } finally { setWorking(false); } };
  const download = async (item) => { try { const response = await api.get(`/api/medical-documents/${item._id}/download`, { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = item.displayName; link.click(); URL.revokeObjectURL(url); } catch (error) { message.error(error.response?.data?.message || 'Unable to download document.'); } };
  const archive = async (id) => { try { await api.delete(`/api/medical-documents/${id}`); message.success('Document archived.'); load(); } catch (error) { message.error(error.response?.data?.message || 'Unable to archive document.'); } };
  return <Card className="care-section-card" title="Secure medical documents"><Form form={form} layout="vertical" onFinish={upload}><Space wrap align="end"><Form.Item name="displayName" label="Document name" rules={[{ required: true }]}><Input placeholder="e.g. Latest prescription" /></Form.Item><Form.Item name="category" label="Category" rules={[{ required: true }]}><Select style={{ width: 190 }} options={['prescription', 'medical_report', 'insurance_card', 'doctor_note', 'vaccination', 'discharge_summary', 'identification'].map((value) => ({ value, label: value.replaceAll('_', ' ') }))} /></Form.Item><Upload beforeUpload={(selected) => { setFile(selected); return false; }} maxCount={1} accept=".pdf,.jpg,.jpeg,.png,.webp"><Button icon={<UploadOutlined />}>Choose file</Button></Upload><Button type="primary" htmlType="submit" loading={working}>Upload securely</Button></Space></Form><List style={{ marginTop: 18 }} dataSource={items} locale={{ emptyText: <Empty description="No documents uploaded" /> }} renderItem={(item) => <List.Item actions={[<Button key="download" type="link" icon={<DownloadOutlined />} onClick={() => download(item)}>Download</Button>, <Button key="archive" danger type="link" icon={<DeleteOutlined />} onClick={() => archive(item._id)}>Archive</Button>]}><List.Item.Meta title={item.displayName} description={`${item.category.replaceAll('_', ' ')} · ${Math.ceil(item.bytes / 1024)} KB · Account owner only`} /></List.Item>} /></Card>;
};
export default MedicalDocuments;
