import React, { useContext, useMemo, useState } from 'react';
import axios from 'axios';
import { toast } from 'react-toastify';
import './MedicalForm.css';
import { AuthContext } from '../context/AuthContext';

const initial={name:'',dob:'',gender:'',bloodGroup:'',height:'',weight:'',dietPreference:'',phone:'+91',emergencyContact:'',emergencyPhone:'+91',address:'',medicalHistory:[],allergies:[],medications:[],currentSymptoms:[],hasInsurance:false,insuranceProvider:'',policyNumber:'',preferredLanguage:'',mobilityStatus:'',fallRisk:false,doctorName:'',doctorPhone:'',preferredHospital:''};
const choices={medicalHistory:['Diabetes','Hypertension','Asthma','Heart Disease','Stroke','Kidney Disease'],allergies:['Penicillin','Aspirin','Food','Dust','Pollen','Latex'],medications:['Metformin','Amlodipine','Insulin','Aspirin','Warfarin','Inhalers'],currentSymptoms:['Dizziness','Chest Pain','Fatigue','Shortness of Breath','Swelling','Joint Pain']};
const steps=['Personal','Contact & emergency','Medical','Insurance & review'];

const MedicalForm=({onSubmissionSuccess})=>{
 const [data,setData]=useState(initial); const [step,setStep]=useState(0); const [saving,setSaving]=useState(false); const [photo,setPhoto]=useState(null); const {user}=useContext(AuthContext);
 const age=useMemo(()=>data.dob?Math.max(0,new Date().getFullYear()-new Date(data.dob).getFullYear()):null,[data.dob]);
 const change=({target})=>setData(v=>({...v,[target.name]:target.type==='checkbox'?target.checked:target.value}));
 const toggle=(field,value)=>setData(v=>({...v,[field]:v[field].includes(value)?v[field].filter(x=>x!==value):[...v[field],value]}));
 const validate=()=>{const required=step===0?['name','dob','gender','height','weight','dietPreference']:step===1?['phone','emergencyContact','emergencyPhone','address']:[]; const missing=required.filter(k=>!String(data[k]).trim()); if(missing.length)toast.error('Complete all required fields before continuing.'); return !missing.length;};
 const next=()=>validate()&&setStep(v=>Math.min(v+1,steps.length-1));
 const submit=async(e)=>{e.preventDefault();if(!validate())return;setSaving(true);try{const token=localStorage.getItem('token');await axios.post(`${process.env.REACT_APP_BACKEND_URI}/api/medical`,data,{headers:{Authorization:`Bearer ${token}`}});if(photo&&user){const body=new FormData();body.append('photo',photo);await axios.post(`${process.env.REACT_APP_BACKEND_URI}/api/medical/${user._id}/photo`,body,{headers:{Authorization:`Bearer ${token}`}});}toast.success('Medical profile saved successfully.');onSubmissionSuccess?.();}catch(error){toast.error(error.response?.data?.message||'Unable to save medical profile.');}finally{setSaving(false);}}; const checks=(field)=><div className="choice-grid">{choices[field].map(item=><label className={data[field].includes(item)?'selected':''} key={item}><input type="checkbox" checked={data[field].includes(item)} onChange={()=>toggle(field,item)}/><span>{item}</span></label>)}</div>;
 return <section className="care-form-shell"><header><div><span className="care-eyebrow">HEALTH PROFILE</span><h2>Medical information</h2><p>Complete one short section at a time. You can review everything before saving.</p></div><strong>{step+1} / {steps.length}</strong></header><ol className="care-progress">{steps.map((label,index)=><li className={index<=step?'active':''} key={label}><button type="button" onClick={()=>index<step&&setStep(index)}><span>{index+1}</span>{label}</button></li>)}</ol><form onSubmit={submit}>
 {step===0&&<fieldset><legend>Personal information</legend><div className="care-grid"><label className="wide">Profile photograph<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]||null)}/><small>JPEG, PNG or WebP, maximum 3 MB</small></label><label>Full name *<input name="name" value={data.name} onChange={change}/></label><label>Date of birth *<input type="date" name="dob" value={data.dob} onChange={change}/><small>{age!==null?`Approximate age: ${age}`:''}</small></label><label>Gender *<select name="gender" value={data.gender} onChange={change}><option value="">Select</option><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option></select></label><label>Blood group<select name="bloodGroup" value={data.bloodGroup} onChange={change}><option value="">Unknown</option>{['A+','A-','B+','B-','AB+','AB-','O+','O-'].map(x=><option key={x}>{x}</option>)}</select></label><label>Height (cm) *<input type="number" min="100" max="250" name="height" value={data.height} onChange={change}/></label><label>Weight (kg) *<input type="number" min="25" max="250" name="weight" value={data.weight} onChange={change}/></label><label>Preferred language<input name="preferredLanguage" value={data.preferredLanguage} onChange={change}/></label><label>Mobility status<select name="mobilityStatus" value={data.mobilityStatus} onChange={change}><option value="">Select</option><option value="independent">Independent</option><option value="walking_aid">Walking aid</option><option value="wheelchair">Wheelchair</option><option value="bed_assistance">Bed assistance</option></select></label><label>Diet preference *<select name="dietPreference" value={data.dietPreference} onChange={change}><option value="">Select</option>{['Vegetarian','Non-Vegetarian','Vegan','Eggetarian'].map(x=><option key={x}>{x}</option>)}</select></label></div></fieldset>}
 {step===1&&<fieldset><legend>Contact and emergency</legend><div className="care-grid"><label>Primary phone *<input name="phone" value={data.phone} onChange={change}/></label><label>Emergency contact name *<input name="emergencyContact" value={data.emergencyContact} onChange={change}/></label><label>Emergency phone *<input name="emergencyPhone" value={data.emergencyPhone} onChange={change}/></label><label className="wide">Residential address *<textarea name="address" value={data.address} onChange={change} rows="4"/></label></div></fieldset>}
 {step===2&&<fieldset><legend>Medical information</legend><h3>Known conditions</h3>{checks('medicalHistory')}<h3>Allergies</h3>{checks('allergies')}<h3>Current medications</h3>{checks('medications')}<h3>Current symptoms</h3>{checks('currentSymptoms')}<div className="care-grid"><label className="care-switch"><input type="checkbox" name="fallRisk" checked={data.fallRisk} onChange={change}/><span>Fall risk</span></label><label>Treating doctor<input name="doctorName" value={data.doctorName} onChange={change}/></label><label>Doctor phone<input name="doctorPhone" value={data.doctorPhone} onChange={change}/></label><label>Preferred hospital<input name="preferredHospital" value={data.preferredHospital} onChange={change}/></label></div></fieldset>}
 {step===3&&<fieldset><legend>Insurance and review</legend><label className="care-switch"><input type="checkbox" name="hasInsurance" checked={data.hasInsurance} onChange={change}/><span>I have health insurance</span></label>{data.hasInsurance&&<div className="care-grid"><label>Insurance provider<input name="insuranceProvider" value={data.insuranceProvider} onChange={change}/></label><label>Policy number<input name="policyNumber" value={data.policyNumber} onChange={change}/></label></div>}<div className="review-card"><h3>Review summary</h3><p><strong>{data.name||'Name not entered'}</strong> · {data.bloodGroup||'Blood group unknown'}</p><p>{data.emergencyContact||'Emergency contact missing'} · {data.emergencyPhone}</p><p>{data.medicalHistory.length} conditions · {data.allergies.length} allergies · {data.medications.length} medications</p></div></fieldset>}
 <div className="care-form-actions">{step>0&&<button type="button" className="secondary" onClick={()=>setStep(v=>v-1)}>Previous</button>}{step<steps.length-1?<button type="button" onClick={next}>Save & continue</button>:<button type="submit" disabled={saving}>{saving?'Saving...':'Save medical profile'}</button>}</div></form></section>;
};
export default MedicalForm;