import React,{useContext} from 'react';
import {Link} from 'react-router-dom';
import {Button,Card,Col,Row,Space,Typography} from 'antd';
import {IdcardOutlined,FileTextOutlined,HeartOutlined,QrcodeOutlined,UserOutlined,ArrowRightOutlined} from '@ant-design/icons';
import {AuthContext} from '../context/AuthContext';
import MedicalForm from '../components/MedicalForm';import QRCodeDisplay from '../components/QRCodeDisplay';import Recommendations from '../components/Recommendations';
const {Title,Text,Paragraph}=Typography;
const actions=[['Emergency ID card','Preview, print and download','/profile',IdcardOutlined],['Medical reports','Latest summary and history','/reports',FileTextOutlined],['Health information','Create or update your profile','#medical-form',HeartOutlined],['Emergency QR','Generate a revocable code','#qr',QrcodeOutlined]];
const Dashboard=()=>{const{user}=useContext(AuthContext);return <main className="care-page"><Card className="care-dashboard-hero" styles={{body:{padding:32}}}><Row align="middle" justify="space-between" gutter={[24,24]}><Col><Text className="care-eyebrow" style={{color:'#bde0d5'}}>ELDERLYCARE MEMBER AREA</Text><Title style={{margin:'8px 0'}}>Welcome, {user?.name||'Member'}</Title><Paragraph type="secondary" style={{margin:0,fontSize:17}}>Keep emergency information accurate and ready when it matters.</Paragraph></Col><Col><Link to="/profile"><Button size="large" icon={<UserOutlined/>}>Open my profile</Button></Link></Col></Row></Card><Row gutter={[18,18]} style={{marginTop:22}}>{actions.map(([title,desc,to,Icon])=><Col xs={24} sm={12} xl={6} key={title}><a href={to} onClick={to.startsWith('/')?e=>{e.preventDefault();window.location.assign(to)}:undefined}><Card className="care-quick-card" hoverable><Space align="start"><Button shape="circle" type="primary" ghost icon={<Icon/>}/><div><Title level={4} style={{margin:'2px 0 5px'}}>{title}</Title><Text type="secondary">{desc}</Text><div style={{marginTop:12,color:'#176b57',fontWeight:700}}>Open <ArrowRightOutlined/></div></div></Space></Card></a></Col>)}</Row><Card id="medical-form" className="care-section-card"><MedicalForm/></Card><Row gutter={[22,22]}><Col xs={24} lg={10}><Card id="qr" className="care-section-card" title={<Space><QrcodeOutlined/>Emergency QR</Space>}><Paragraph>Generate a random, revocable emergency-access code after saving your profile.</Paragraph><QRCodeDisplay/></Card></Col><Col xs={24} lg={14}><Card className="care-section-card" title={<Space><HeartOutlined/>Health recommendations</Space>}><Recommendations/></Card></Col></Row></main>};export default Dashboard;
