import React,{useContext,useState} from 'react';
import axios from 'axios';
import {Link,useNavigate} from 'react-router-dom';
import {Alert,Button,Card,Form,Input,Space,Typography} from 'antd';
import {LockOutlined,MailOutlined,SafetyCertificateOutlined} from '@ant-design/icons';
import {AuthContext} from '../context/AuthContext';
import {toast} from 'react-toastify';
const {Title,Text}=Typography;
const Login=()=>{const[loading,setLoading]=useState(false);const[error,setError]=useState('');const{login}=useContext(AuthContext);const navigate=useNavigate();const submit=async(values)=>{setLoading(true);setError('');try{const{data}=await axios.post(`${process.env.REACT_APP_BACKEND_URI}/api/auth/login`,values);localStorage.setItem('token',data.token);login(data.user);toast.success('Login successful');navigate('/dashboard');}catch(requestError){const message=requestError.response?.data?.message||'Login failed. Check your details and try again.';setError(message);toast.error(message);}finally{setLoading(false)}};return <main className="care-auth-page"><Card className="care-auth-card" styles={{body:{padding:32}}}><div className="care-auth-brand"><span className="care-auth-logo"><SafetyCertificateOutlined/></span><div><Text className="care-eyebrow">ELDERLYCARE</Text><br/><Text type="secondary">Secure member access</Text></div></div><Title level={2}>Welcome back</Title><Text type="secondary">Sign in with your email and password to manage emergency health information.</Text>{error&&<Alert style={{marginTop:20}} type="error" showIcon message={error}/>}<Form layout="vertical" requiredMark="optional" onFinish={submit} style={{marginTop:24}}><Form.Item label="Email address" name="email" rules={[{required:true,message:'Enter your email address'},{type:'email',message:'Enter a valid email address'}]}><Input prefix={<MailOutlined/>} autoComplete="email" placeholder="you@example.com"/></Form.Item><Form.Item label="Password" name="password" rules={[{required:true,message:'Enter your password'}]}><Input.Password prefix={<LockOutlined/>} autoComplete="current-password" placeholder="Your password"/></Form.Item><Button type="primary" htmlType="submit" loading={loading} block>Sign in securely</Button></Form><Space direction="vertical" size={6} className="care-auth-footer" style={{width:'100%'}}><Text>Forgot password? <Link to="/contact">Contact support</Link></Text><Text>New to ElderlyCare? <Link to="/register">Create an account</Link></Text><Button type="link" onClick={()=>navigate('/')}>Return home</Button></Space></Card></main>};export default Login;
